---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: install java
    ansible.builtin.apt:
      name: openjdk-17-jre
      state: present
  - name: download maven package 
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
  - name: extract maven package
    ansible.builtin.unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
      remote_src: yes